services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Stores the data in this path. This causes data to persist even when container is shut down.

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: