name: CI - Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches # The directory where Gradle stores dependencies
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          # If an exact match isn't found, use the most recent cache
          restore-keys: |
            gradle-${{ runner.os }}- 

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew # Ensures the Gradle wrapper script is executable

      - name: Run tests
        run: ./gradlew test
